In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import statistics
import statsmodels.api as sm
from scipy.stats import norm
from scipy.stats import t

In [ ]:
# 8

In [4]:
df1 = pd.read_excel('Данные для тестового задания.xlsx',sheet_name = 1)

In [5]:
df1.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [7]:
for exp in [1,2,3]:
    data = df1[df1['experiment_num']==exp]
    test =data[data['experiment_group']=='test']['revenue']
    control = data[data['experiment_group']=='control']['revenue']
    test_mean = np.mean(test)
    control_mean= np.mean(control)
    
    test_std = np.std(test, ddof=1)
    control_std = np.std(control, ddof=1)

    test_size= len(test)
    control_size = len(control)

    dof = test_size + control_size - 2

    err_diff = np.sqrt(test_std**2/test_size +control_std**2/control_size)

    diff_mean= test_mean - control_mean
    t_stat = diff_mean / err_diff

    p_value = 2*(1-t.cdf(abs(t_stat), dof))

    print("Experiment",exp)
    print("t_stat=", t_stat)
    print("p_value=", p_value)
    print()

Experiment 1
t_stat= -0.4003821709709455
p_value= 0.688965739915389

Experiment 2
t_stat= -3.270721407077592
p_value= 0.0011116175021730346

Experiment 3
t_stat= 1.880979190694145
p_value= 0.060282673317706426

In [ ]:
# 9

In [5]:
df2 = pd.read_excel('Данные для тестового задания.xlsx',sheet_name = 2)

In [6]:
df2.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [7]:
df2.describe()

,user_id,date,cnt_adverts,age,cnt_contacts,revenue
count,158.000000,158,158.000000,158.000000,158.000000,158.000000
mean,115.101266,2022-01-14 12:45:34.177215232,2.886076,27.424051,94.031646,30.702532
min,100.000000,2022-01-01 00:00:00,0.000000,20.000000,0.000000,0.000000
25%,107.000000,2022-01-07 00:00:00,1.000000,22.750000,42.000000,17.000000
50%,115.000000,2022-01-14 00:00:00,3.000000,28.000000,92.500000,31.000000
75%,123.000000,2022-01-21 18:00:00,5.000000,31.000000,148.500000,45.000000
max,130.000000,2022-01-30 00:00:00,6.000000,36.000000,200.000000,60.000000
std,9.008976,NaN,2.028380,4.640303,60.231128,16.575060

In [10]:
mean = df2['revenue'].sum() /df2['user_id'].nunique()
print(mean)

156.48387096774192

In [11]:
df2['age'].median()

28.0